### ISSUE TITLE
TeamCity Professional 2024.12 (build 174331) fails to make premerge step

### ISSUE THREAD

**Issue by szagurskii** [JetBrains/teamcity-premerge#3]
```
  java.lang.NoSuchMethodError: 'void jetbrains.buildServer.buildTriggers.vcs.git.agent.BuildContext.<init>(jetbrains.buildServer.agent.AgentRunningBuild, jetbrains.buildServer.buildTriggers.vcs.git.agent.AgentPluginConfig)'
    at jetbrains.buildServer.premerge.PremergeBranchSupportImpl.getFacade(PremergeBranchSupportImpl.java:72)
    at jetbrains.buildServer.premerge.PremergeBranchSupportImpl.<init>(PremergeBranchSupportImpl.java:55)
    at jetbrains.buildServer.premerge.PremergeBuildProcess.createPremergeBranchSupport(PremergeBuildProcess.java:126)
    at jetbrains.buildServer.premerge.PremergeBuildProcess.makeVcsRootPreliminaryMerge(PremergeBuildProcess.java:96)
    at jetbrains.buildServer.premerge.PremergeBuildProcess.preliminaryMerge(PremergeBuildProcess.java:85)
    at jetbrains.buildServer.premerge.PremergeBuildProcess.start(PremergeBuildProcess.java:74)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:60)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:27)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.executeBuildStepStages(RunnerContextExecutor.java:45)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.runBuildStep(RunAllBuildStepsStage.java:195)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.runStep(RunAllBuildStepsStage.java:181)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.executeBuildRunners(RunAllBuildStepsStage.java:131)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.doBuildStage(RunAllBuildStepsStage.java:58)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:33)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:97)
    at jetbrains.buildServer.agent.AgentOperationModeEx.executeRunnerStages(AgentOperationModeEx.java:47)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:68)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:350)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:62)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:299)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by szagurskii** [comment]
@manturovDan Do you think you can fix this one in the near future?

**Comment by manturovDan** [comment]
@szagurskii Yes, I hope this week

**Comment by manturovDan** [comment]
Hello @szagurskii  sorry for the delay. I have fixed the plugin (https://plugins.jetbrains.com/plugin/18597-preliminary-merge/edit/versions/stable/677749)
